-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.3
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity standalone_mmult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_ce0 : OUT STD_LOGIC;
    B_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_ce0 : OUT STD_LOGIC;
    C_we0 : OUT STD_LOGIC;
    C_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of standalone_mmult is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "standalone_mmult,hls_ip_2016_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.412000,HLS_SYN_LAT=329793,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=5,HLS_SYN_FF=483,HLS_SYN_LUT=830}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_4_cast_fu_142_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_4_cast_reg_232 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ia_fu_152_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ia_reg_241 : STD_LOGIC_VECTOR (5 downto 0);
    signal ib_0_i_cast2_cast_fu_158_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ib_0_i_cast2_cast_reg_246 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal C_addr_reg_251 : STD_LOGIC_VECTOR (9 downto 0);
    signal ib_fu_178_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ib_reg_259 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal id_fu_226_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal id_reg_277 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_128_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_292 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fu_123_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ia_0_i_reg_77 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond1_i_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ib_0_i_reg_88 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond2_i_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_i_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_0_i_reg_99 : STD_LOGIC_VECTOR (31 downto 0);
    signal id_0_i_reg_112 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_5_cast_fu_167_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_cast_fu_193_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_cast_fu_215_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal tmp_3_fu_134_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_162_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal id_0_i_cast1_cast_fu_184_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_6_fu_188_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_7_fu_198_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_8_cast_fu_206_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_9_fu_210_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);

    component standalone_mmult_bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component standalone_mmult_cud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    standalone_mmult_bkb_U0 : component standalone_mmult_bkb
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sum_0_i_reg_99,
        din1 => tmp_reg_292,
        ce => ap_const_logic_1,
        dout => grp_fu_123_p2);

    standalone_mmult_cud_U1 : component standalone_mmult_cud
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => A_q0,
        din1 => B_q0,
        ce => ap_const_logic_1,
        dout => grp_fu_128_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ia_0_i_reg_77_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state3) and not((exitcond1_i_fu_172_p2 = ap_const_lv1_0)))) then 
                ia_0_i_reg_77 <= ia_reg_241;
            elsif (((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_start = ap_const_logic_0)))) then 
                ia_0_i_reg_77 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    ib_0_i_reg_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state4) and not((ap_const_lv1_0 = exitcond_i_fu_220_p2)))) then 
                ib_0_i_reg_88 <= ib_reg_259;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state2) and (ap_const_lv1_0 = exitcond2_i_fu_146_p2))) then 
                ib_0_i_reg_88 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    id_0_i_reg_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state13))) then 
                id_0_i_reg_112 <= id_reg_277;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state3) and (exitcond1_i_fu_172_p2 = ap_const_lv1_0))) then 
                id_0_i_reg_112 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    sum_0_i_reg_99_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state13))) then 
                sum_0_i_reg_99 <= grp_fu_123_p2;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state3) and (exitcond1_i_fu_172_p2 = ap_const_lv1_0))) then 
                sum_0_i_reg_99 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state3))) then
                C_addr_reg_251 <= tmp_5_cast_fu_167_p1(10 - 1 downto 0);
                    ib_0_i_cast2_cast_reg_246(5 downto 0) <= ib_0_i_cast2_cast_fu_158_p1(5 downto 0);
                ib_reg_259 <= ib_fu_178_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state2))) then
                ia_reg_241 <= ia_fu_152_p2;
                    tmp_4_cast_reg_232(10 downto 5) <= tmp_4_cast_fu_142_p1(10 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state4))) then
                id_reg_277 <= id_fu_226_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state8))) then
                tmp_reg_292 <= grp_fu_128_p2;
            end if;
        end if;
    end process;
    tmp_4_cast_reg_232(4 downto 0) <= "00000";
    tmp_4_cast_reg_232(11) <= '0';
    ib_0_i_cast2_cast_reg_246(11 downto 6) <= "000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, exitcond1_i_fu_172_p2, exitcond2_i_fu_146_p2, exitcond_i_fu_220_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (not((ap_const_lv1_0 = exitcond2_i_fu_146_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (not((exitcond1_i_fu_172_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (not((ap_const_lv1_0 = exitcond_i_fu_220_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    A_address0 <= tmp_6_cast_fu_193_p1(10 - 1 downto 0);

    A_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state4))) then 
            A_ce0 <= ap_const_logic_1;
        else 
            A_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    B_address0 <= tmp_9_cast_fu_215_p1(10 - 1 downto 0);

    B_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state4))) then 
            B_ce0 <= ap_const_logic_1;
        else 
            B_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    C_address0 <= C_addr_reg_251;

    C_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state4))) then 
            C_ce0 <= ap_const_logic_1;
        else 
            C_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    C_d0 <= sum_0_i_reg_99;

    C_we0_assign_proc : process(ap_CS_fsm_state4, exitcond_i_fu_220_p2)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state4) and not((ap_const_lv1_0 = exitcond_i_fu_220_p2))))) then 
            C_we0 <= ap_const_logic_1;
        else 
            C_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0 downto 0);
    ap_CS_fsm_state13 <= ap_CS_fsm(12 downto 12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1 downto 1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2 downto 2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3 downto 3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4 downto 4);
    ap_CS_fsm_state8 <= ap_CS_fsm(7 downto 7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8 downto 8);

    ap_done_assign_proc : process(ap_CS_fsm_state2, exitcond2_i_fu_146_p2)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state2) and not((ap_const_lv1_0 = exitcond2_i_fu_146_p2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond2_i_fu_146_p2)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state2) and not((ap_const_lv1_0 = exitcond2_i_fu_146_p2)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    exitcond1_i_fu_172_p2 <= "1" when (ib_0_i_reg_88 = ap_const_lv6_20) else "0";
    exitcond2_i_fu_146_p2 <= "1" when (ia_0_i_reg_77 = ap_const_lv6_20) else "0";
    exitcond_i_fu_220_p2 <= "1" when (id_0_i_reg_112 = ap_const_lv6_20) else "0";
    ia_fu_152_p2 <= std_logic_vector(unsigned(ia_0_i_reg_77) + unsigned(ap_const_lv6_1));
    ib_0_i_cast2_cast_fu_158_p1 <= std_logic_vector(resize(unsigned(ib_0_i_reg_88),12));
    ib_fu_178_p2 <= std_logic_vector(unsigned(ib_0_i_reg_88) + unsigned(ap_const_lv6_1));
    id_0_i_cast1_cast_fu_184_p1 <= std_logic_vector(resize(unsigned(id_0_i_reg_112),12));
    id_fu_226_p2 <= std_logic_vector(unsigned(id_0_i_reg_112) + unsigned(ap_const_lv6_1));
    tmp_3_fu_134_p3 <= (ia_0_i_reg_77 & ap_const_lv5_0);
    tmp_4_cast_fu_142_p1 <= std_logic_vector(resize(unsigned(tmp_3_fu_134_p3),12));
    tmp_5_cast_fu_167_p1 <= std_logic_vector(resize(unsigned(tmp_5_fu_162_p2),32));
    tmp_5_fu_162_p2 <= std_logic_vector(unsigned(tmp_4_cast_reg_232) + unsigned(ib_0_i_cast2_cast_fu_158_p1));
    tmp_6_cast_fu_193_p1 <= std_logic_vector(resize(unsigned(tmp_6_fu_188_p2),32));
    tmp_6_fu_188_p2 <= std_logic_vector(unsigned(id_0_i_cast1_cast_fu_184_p1) + unsigned(tmp_4_cast_reg_232));
    tmp_7_fu_198_p3 <= (id_0_i_reg_112 & ap_const_lv5_0);
    tmp_8_cast_fu_206_p1 <= std_logic_vector(resize(unsigned(tmp_7_fu_198_p3),12));
    tmp_9_cast_fu_215_p1 <= std_logic_vector(resize(unsigned(tmp_9_fu_210_p2),32));
    tmp_9_fu_210_p2 <= std_logic_vector(unsigned(ib_0_i_cast2_cast_reg_246) + unsigned(tmp_8_cast_fu_206_p1));
end behav;
